### ISSUE TITLE
As a student, i want to be able to register in the application to participate in the activities developed by the teacher within the application

### ISSUE THREAD

**Issue by tulioc** [TecProgPurrsuit/TeamBasedLearningApp#1]
# Done Condition: 

### The user must provide: 
 - Name
 - Registration number
 - Group Number
 - Name of the class
 - Password
 - Is Teacher?

### Pre-requisites to complete the issue:

- [x] Create authentication login
- [x] Create authentication logout
- [x] Create authentication register
- [x] Get current user without reload the page
- [X] Improving the layout of authentication component
- [X] Insert new fields to authentication
- [ ] Create authentication send email to change password
- [ ] make tests
- [ ] Insert CustomMessagem on main page
- [ ] Fix register validation error
- [ ] Register groups and classes on database
- [ ] Insert a profile to user/teacher
